---
compileVersionKey: "1.0.0"

spring:
    data:
        mongodb:
            database: kogo_content_backend
            uri: mongodb://localhost:27017/kogo-content-backend
            username: admin
            password: password
            auto-index-creation: true

filehandler:
    prefix: tmp/files
