kogo-api:
    authenticate: ENC[AES256_GCM,data:k3sXaiNwul90kShXuC1ctEI7yB60gso/Y7ZXLKDM1mzQ9XQF+oSpLMwZdWpTg5I=,iv:YyizbGkVlWgqUIrj1kVNVR3TtTjoWw1m1idve/FHrcs=,tag:E7ibVaubUJ/tQfOO0ABV7g==,type:str]
    getSchools: ENC[AES256_GCM,data:vH1PVwOP6xMyEM+vGw56IJGH/cQLyufr5P4mtHlCeoYncIGIvK5j2c6m,iv:trecM3irbs+/5Tla90L0Stve5tYiFIDhACkig9VJbpo=,tag:aGqPSQqjVWpqbjxuTxiHjA==,type:str]
    uploadFiles: ENC[AES256_GCM,data:lKa6y3tMjDL728z9ONeQWNSUd5+w,iv:hYkQi5rxTpMNpqLmNuyxlhpwcZN/6vdOow8WEeLv5Iw=,tag:WyuR5ZUAgWSqCCUWqr+yWQ==,type:str]
security:
    secret-key: ENC[AES256_GCM,data:mj/LAASmQiBSXPSADrkSp0KWxlRF5Z2Y3tueoUJo/0030r/TB1e20YTOiw==,iv:GCePf3nJMfgLJ5w1U4XDwtsvOBPw/QNIcYfVacVsvIU=,tag:nCJ21bhuZTJFC1/JBU5EBw==,type:str]
spring:
    data:
        mongodb:
            database: ENC[AES256_GCM,data:PB8gIrOgCd0dJmFF2MAl9h5kkUM=,iv:2ZItNc3X8N0pFtlyFaOlsDu2onE4lr7vagqHGK/j8WI=,tag:B4+23KIsweiIBjcmUZ7aWA==,type:str]
            uri: ENC[AES256_GCM,data:nVWWlTKBncswNFySQbPbQleMAllq6bXbBuQZvK+gOli4o05EsSoqOV2HR4nNVRc9jnlcb/ZmTwpjx3VcNdVc81H/Ekxl6HWF5Ie3UThIYMwFMoraDoq6aFARacLQn9qsXZwMUUln0lMuAocGAmeCr/h3HCOtRfaqxXz3mDQvtiAdUKkVSAd1XdonKS8t30iqLuQ5DnAYemZd3IAQdE73/hMPvOrHaS5LKExm4JtdcoD8,iv:EbIv4zKvdelZGksWiST29V2yAg6Xn4TCki/zuLakT8w=,tag:es+WzAoEt+2L0N2tCTGi3g==,type:str]
            username: ENC[AES256_GCM,data:lV8QxRhgBL+pbIiiU3puQR8=,iv:zmd3OgCI1SzR8a/jaEm+xdln0Jv724VO/WfwGAMBw8k=,tag:EMlZsKLe0x9xbg9vS1bZ4A==,type:str]
            password: ENC[AES256_GCM,data:MtKwnGiIRei46ArYfTyyRw==,iv:M0Ffw3OnUlyqD8h6RwJSSz5C7NqE6cjVwu5rxz8ujmM=,tag:2xu/LnRztUEIJl4ale6pEQ==,type:str]
            auto-index-creation: ENC[AES256_GCM,data:o6d8Sg==,iv:Uk39D67R3fJwxi9b44vh8cB347TIbf5hLPE4dSHvAa4=,tag:O48bWlsVJ6QpSR7YLy6g+A==,type:bool]
sentry:
    dsn: ENC[AES256_GCM,data:kuSe/bLgEtxDixlB3NdHFC0oVrHt3FpXQtjfwp8DCQQd+zGCVrmwgcaoLjvHDfD9imc4dg27rwJdAaVSzl4LSqkdMTlNH0xhXYGGp4eb0QEEBmq+ol7Q5g/8bIOEmOw=,iv:0Zhsv6W10JmGUYDtI3TUwRQI+xB4bg7hvrVgVHISx24=,tag:xHv3Im1mgT2pHeQybQBXfw==,type:str]
    traces-sample-rate: ENC[AES256_GCM,data:5A==,iv:68PwdoIoqotkRcEXzd0TkluNZmJOP5T3CNIGIND/Vu8=,tag:5PGbN9iY+/7UHHqqV2jXQw==,type:int]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:992382730467:key/a195f3cb-f301-48b4-ba70-9ffb95f6ddd2
          created_at: "2025-02-19T15:43:18Z"
          enc: AQICAHhZgrxm0DnTWfKW65/rZF7H04iuSIwsXgTk9YAalC3+YQE408sTAIR9Aw8ahEi+X8DmAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMVap2zJeJM6oFxrX7AgEQgDu9zurSmCgUG9ickR4M10iRuwSO6R7GpogvjzXjUqJ2qryX4XuZ2SrE7uvV1uWg29E0g3W+C+xMYg+CCA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-19T15:43:18Z"
    mac: ENC[AES256_GCM,data:5Q7fN7dyfaUvLWt6WsgCXlyTsubHXKFYL2MNXq7te/SlixcCyuLFwLvb5zcSZlvwFqm+OkDXjmDDR1uKw77huHaCloYdV2EC5sNVScDrnMZ67dbRg+ZI7JU0FpQRW4NGLAiNmqKES5WJb/QuSi/q7hhE1UYYuAsk5c1s84V/2JA=,iv:2SdJv01w+gMRsXlPrOOuPMF5U6Rck33YfQHl+gw6rsA=,tag:LRsnK60N7SjegWqhCZPEEw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
