kogo-api:
    authenticate: ENC[AES256_GCM,data:QFZoS8DbWMG1qjX1vjJvilsyijjahsdDT0BJtdXRllzc8Pg8An8pNTH7cMmcJdQ=,iv:5VqnSM/UB2iUK7JYyeLgxza7u7sZpWUUwT5BT7BC+88=,tag:/9Lk10oZ+XV4vrwUm2qFgw==,type:str]
    getSchools: ENC[AES256_GCM,data:ZrPhovzp7ZxrdOqC2pFGROab7YYsS1ot28D2Jrm8B7nOx5O0O5D/KV6x,iv:D4cloji/WLDL7KWMO9/xiilmDt7cIBdkkRoupUyoTfA=,tag:Mw4JMLNUaJlMPPyQmrIhRw==,type:str]
    uploadFiles: ENC[AES256_GCM,data:OnccwCDn5I82CIn6x+G3bpG+z1Gz,iv:LYjXuJJ82HUpzk5jJXtuuHyaEJ0ivs9ZxduGnsOJ8d4=,tag:La7VkZ5ys7+PqZk8SaPflQ==,type:str]
security:
    secret-key: "S33KrcdZ8uua2tsGFkpzWnu4Q4Mu31P7QWf3A7BD050"
spring:
    data:
        mongodb:
            database: ENC[AES256_GCM,data:RrYCSQj/OsvP0TfAobViexfvHlA=,iv:KmvrtM9Gt7znIr23Amy6yHASjLP4i4+qa4JAmHQ4iEU=,tag:aGcGEdBO6uI+wYMHEh3xSw==,type:str]
            uri: ENC[AES256_GCM,data:vVV9hdb4ws2bFSCXEqXUbixTBXi0x0GaAxupPbHGXyetmve+AiZ/efoWT2O7ECJsX0T9AEYrHJY8jIRGoi6h1ePXVS8nvlOXCD9OT7mPghTdwJpgWgzea/ReNmU9Ja+5Z2NAt/w2QEKc5UMSvXhg2iEfzAodfvgD9HzwekH/rpKoG0wrgEbd55m2W7+aUrkd039R0hPS3W9u7eH+n0TNOcowo59hZpIrnnFD47+7r0Wh,iv:djvlPuMlf2FZGxmRmS0VK48UrOxg+XY/PtFPjXiwJ9U=,tag:guHomb+vsG9tK/ZOiJ2Ztw==,type:str]
            username: ENC[AES256_GCM,data:49TRjk3blPhGTKXqbW436vw=,iv:Ojw3B7LbM3xemOebekC5vLYA5qLwDHjNciJDd1QvRgw=,tag:l7eW/AIzB6GwY5anmxmGLg==,type:str]
            password: ENC[AES256_GCM,data:ncmXg7q7uC2iiFPMx93QAg==,iv:Xb3soU6PYZUBpGg6VH3dypcHVmezGkCQJg+deA+HdI0=,tag:u9MVlMosQIWMJwalfBGaXg==,type:str]
            auto-index-creation: ENC[AES256_GCM,data:RC5XlA==,iv:NQEtq/sj5CpiAYU4QRFLUv9T3VSPp3GmHQln+oqPwxw=,tag:jy+pAi11X9LvOw019IJTgg==,type:bool]
sentry:
    dsn: ENC[AES256_GCM,data:Go7SA8RcjO4iK8h5taPM/UyLTRI1dqci+ZwUwrXkfCt4NczcTwlMuYhDbvoSwf0bh9mKL6nD+TEU61Au02N+jnKZCUh3vnU4ooiQK2ak7D1uFKqqWLJC2nltbIUVkLQ=,iv:oTXXGD2vl6prTY/klHGlQL5rn3Kh74CnqNqVbuP9u3s=,tag:gOjc1rt8jDghV86Iz9S0bA==,type:str]
    traces-sample-rate: ENC[AES256_GCM,data:SQ==,iv:yev8FZLg9C6XqlWAYmgYa1unFjdFOeHREgcdmXrdndo=,tag:1KZrkJhm90YFh+188arCgg==,type:int]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:992382730467:key/a195f3cb-f301-48b4-ba70-9ffb95f6ddd2
          created_at: "2025-01-20T22:22:15Z"
          enc: AQICAHhZgrxm0DnTWfKW65/rZF7H04iuSIwsXgTk9YAalC3+YQFY2THneu5OFodUhfs/KoQ1AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMXdZiap9TvS3IYTKOAgEQgDvkuXEneTb/eus269w3ekiG9f0SD2TPAnPdhcR1trWo1V6oKintGY1QRnLDn1+Oic8igkIGTlZqMP9OWA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-20T22:22:16Z"
    mac: ENC[AES256_GCM,data:jRQNrxwK5dnP8rIdmbcBhReFkwmxmvuDq7nmmbv1dZLABTFbwd+yiinmqG6PP4EBFa405jZLyPEU2uvH3HcFt7JW2IK89v/TKrnriBcEokNP5EnC08OUp4EgGZEHqz49Egzz3zEwslDFpDL9LTBaoGC8qjY3r1CRzZUWSF5xbUE=,iv:0MITrfHsNEc3o0rn+dUhP9ONQGN6ij3jCJ5xMHS2P/I=,tag:0I58TfKcKlwMKjGgfryEcw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
