kogo-api:
    authenticate: ENC[AES256_GCM,data:wf55+yopTTipOBvZQHKIqyMNzAHNBnoM+6SohopEvr6RV7fF+6eMe2SSf4HedmA=,iv:yjG4CNOr/8syXGccn2BYhHRrux1zHgNMrVFRAZ7EyvI=,tag:eyovHQShWtOSPNRu6l5Zyw==,type:str]
spring:
    data:
        mongodb:
            database: ENC[AES256_GCM,data:Fg+NNfLI19l73mWO+F8hnKLwMJY=,iv:1yixf28TKCltw2Vh/zCpwTgssC3eWzJP4izm1F5JwQc=,tag:0kYMP3FEUrv01TyeBgU+tw==,type:str]
            uri: ENC[AES256_GCM,data:5lGHJHcQ6gnfb/Jb1lID3UckfjnL/7DhDI0cCjLZmpW95UKytrNC/zr6bYMN4zPV6FV4ehbqbYpuuf47r+CwOMTs/OmSg4VQiI7O57cW3dIBzvXYS0CsogKsDIfI7jxlCbFtt2aB7/wFKdjD7LCYEr8qXNJHMG/IX6PRXbvVDERrSO1abMsUn3rBgMndbAdTQpnsKT444he4VdUcQgtPKUQ8QmzaWG1KThdKEXjX1b4htWemB6+LhA2q9uyyiA==,iv:VAugIXd6eMZEQq09rm0rmtW5UIiFBAix9zz3HyeUEwk=,tag:xD33bTtyEapkMduxrYmGDg==,type:str]
            username: ENC[AES256_GCM,data:rStHcGVobWXi9Jz2D4QFYyI=,iv:8ugm3YxWZ18dvvxF6xcy5AdmzfxYRl5rg3p/zycLHUA=,tag:lAzOUqtYCNijWxdOTCSTEA==,type:str]
            password: ENC[AES256_GCM,data:ByKI9lEGP0g+uinKLAynPA==,iv:Sp4Wips38ls/Zo8XbhVyBH6JpMkXaKs/P07EKCB4z3s=,tag:73/KQ8Mj3foNJMDaflAwEQ==,type:str]
            auto-index-creation: ENC[AES256_GCM,data:DC0YRA==,iv:8gH9j/oh6r/w7Kj7zqb44QxxUHupvarXnZiQCmfKH2E=,tag:FFtE4w5D2nKCU3keSQ36/A==,type:bool]
sentry:
    dsn: ENC[AES256_GCM,data:aD4MA+JWESy7OiXLvjAgDnG0hnRa1ig399KaPcWopDLDNCkVREiWq9g/RR4ktUwZOXA6eHaBbBFd984az3aiJjIqZZ2RDDOriYkLKJQhO9M429eZ3WR3LJafeiMFIqQ=,iv:njIFvgOHGGt0Erzso2OS6Oax7rXnIhdnvUO/P6JOTDA=,tag:oP97rkmfXXdPqMHWknJGBQ==,type:str]
    traces-sample-rate: ENC[AES256_GCM,data:Dg==,iv:KXvvVVGpR6pqgNV4E2bPLBWZvZFwutqaqBW2/T8SryQ=,tag:LQJtTJVDEDG6NNfik+6avQ==,type:int]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:992382730467:key/a195f3cb-f301-48b4-ba70-9ffb95f6ddd2
          created_at: "2024-12-24T04:40:52Z"
          enc: AQICAHhZgrxm0DnTWfKW65/rZF7H04iuSIwsXgTk9YAalC3+YQHEPcGcrpw/4E818ZirZ79KAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMJBXlvUd6OhjhlxuNAgEQgDtMLOjFCKuVr+TWIw6zxXU4QApys3zBkw3sxG0pu8cZw2BcGXC0xJJ/aSAbi0pw3tWBEH66xLUsBDJkZQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-24T04:40:52Z"
    mac: ENC[AES256_GCM,data:vUSF0NFMxwGsID7yE0JZrWIrBciqJzw+g3CmWtXc0sHActkqDicM1GZ83Mtk+xFXeLqAR3DzgoYtjJrBPVzDUDNLbvfTy+1++LKU8ofoQqXb7Pw/HE0RLMIr6ZdpLXRn5H9/ctqLEN4XSslg6ShpaBiGayL+n6BZflrcu83/0gk=,iv:56iwaHUMBFgCVKseDWPkuhCVDmJ71uDUHY7r6UP7I7Y=,tag:cy/oWcOKQkgVxK69KlUIdA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
