kogo-api:
    authenticate: ENC[AES256_GCM,data:DT0H/XX09dozXpk3j3bcaAJ3O163MDRl9JOrPKgI1tgg5s8KfapUgyDDhcK1kJw=,iv:PDyCpGHpF/i6z7VO+8heahfpKh5UzqhuSjYr5Ew29rk=,tag:URI1+EcCXlxcXbB0EfuHjw==,type:str]
spring:
    data:
        mongodb:
            database: ENC[AES256_GCM,data:3o9IWD/CFj/iCX0QtBIdNALBqcY=,iv:yyUdl1gr3Q6SXX7AVCHBpmQOh2tRECraF/UvmhraY1Y=,tag:21PffxIS3+yGS2M7oFiP+g==,type:str]
            uri: ENC[AES256_GCM,data:KQl4pqFNoc0B9Q1JuNPaCXi+DWlVDp2AevLY6DpHuInIwnQAf9LBfUDg6OUUDj7fD0uy8+KlpIuq8r3rn3baIfvlMx0a9FpJ5Cnkn3DeVjkXE1azw7ohxIgnzkAHbPaP7cm0DH1O+RRJg+cOOSyqhB3EtOgWcMETVmJj48z+hneZcpDihumTV5wRF9VbA49DSNUnU83OYxqwOq9kPVAeHJcIe14rNzp9svRtr6Drp91TBHE=,iv:J0C41La4cMZTKlgCii0ZdUOzTg1g40p0dVxirKYbUTc=,tag:2jHE4LlWC4TfXc30oEkJzA==,type:str]
            username: ENC[AES256_GCM,data:9lg+s4HPLNvSyw9Pp5Nz+GU=,iv:T6nKUbz2ESMT9U8wnKseyRShLrqaGiKQ1ZJsjuR6z8k=,tag:YOZbUYyx7QJpW/+IEHyiWg==,type:str]
            password: ENC[AES256_GCM,data:7bfr4gzTFsWo6h+M169EBQ==,iv:RLC5IkQOAsaqy4nMuB/6CLdE1BRGmKiCF6To/5krPuI=,tag:3/zNRars4WxS9AHSfR8MqA==,type:str]
            auto-index-creation: ENC[AES256_GCM,data:CcJIZA==,iv:vxp4Sac1Buf46X1jH1gp932F0CUKkMRgaxDtJdHuc98=,tag:GcgClBK3h1QsF16efYT7Nw==,type:bool]
sentry:
    dsn: ENC[AES256_GCM,data:Dq0HoXQ6rfbtmVvH4hxK+bM8lLX1grH+av69N3lK0UL7ghgUmLbKcMRGnUHYY+76jQhXUfZi2V7wGh41YKkJhEhqcAfbhEZyRL5KsEM9M3M+TWsn8JujM4LhqYiF5OA=,iv:shZU0qi1vOohj9akjIBRCLunSKrwyN6qiW1dHdFlUk4=,tag:QxYCwV5l8jPskT2ND1Zjjg==,type:str]
    traces-sample-rate: ENC[AES256_GCM,data:1A==,iv:5KPu6yrfND2unPdH1WXzAXfEURDcz875HVi/Jz11xxM=,tag:fFFazkdzh64kWEOvEo+/fw==,type:int]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:992382730467:key/a195f3cb-f301-48b4-ba70-9ffb95f6ddd2
          created_at: "2024-12-24T18:00:42Z"
          enc: AQICAHhZgrxm0DnTWfKW65/rZF7H04iuSIwsXgTk9YAalC3+YQFh8nXuevU8+1fLXccy7BdgAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMZDVg47+BeLo3S0oNAgEQgDs6l8FCAOedIkmihIdfMocJ1ZMtzH48EIQDju4/a6mt1AQFOiSMFwV9N8VMoZSzoO2D4HiTguwz833odw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-24T18:00:43Z"
    mac: ENC[AES256_GCM,data:iWAUvluMeB7y48EprXFE0JtYbykCklbzFBrlBphwTqXt1W5yet/ASAfa5rc6vTErX1FrkVwBOLitx5LQE0qwqrYacmJ1qIuMrkpM3KWpDaQoXi81d0S+TRk0SUE5joXhL0OPAvLEAlI+5VL4fyWNzJZ6U7AuPDk9txi02DRc5kY=,iv:ad56jn3ij5EaviBL/x2Ng/hCFhe06hZnVvVW5BJZXTQ=,tag:m/ODAK2Z8+KtS5bDHSSfBg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
