kogo-api:
    authenticate: ENC[AES256_GCM,data:+i1UVxcRlutcY1FpvgNwxI6DuOJ+73Qad0txu3BFf5cVZ0+2ULScgr38Q9lGMwU=,iv:fcqLtFAolB7OKSNmFC9DnMC2FvIUYnxztdA0+fcqfY8=,tag:l0q5O8GqORFNKMlZOh3o+Q==,type:str]
spring:
    data:
        mongodb:
            database: ENC[AES256_GCM,data:MRwUvTE51CBxqIJUzTWbnr3PNxg=,iv:rJjNk/jqaHfX0PQSNCao7aMAdicmZiQ+3TE5OodtPAg=,tag:wMu/CqJlEMtzvhWIDbFrvg==,type:str]
            uri: ENC[AES256_GCM,data:MMbPl5eIEJ4yKtSZLS0lc2HO6JH/JPPwiZlKJNEFpUQqErldwla+q0ymXV5wvrWT4gWl11KdQhNdlsSP+iB9/SKRUqgKJfUt1TyCW1qEoEeICBRWRbIxp91d6nPLAil/KTLN4Rh0iEpXqFO626em3bZoXP8RWev06exbW15Ug9tZERzPXUv87Kg7ve9VRPYMoLWXQEP/1SfCuwzT3T34NsuUVkBh3+J4sLybA3DJEAMrXlX0BTxyArh687/jtA==,iv:uAPILKRSoGEfpvaYthLyePix1euDUAQTxghiB/bUtx8=,tag:g5tMf3wswwrgQZBz2H1QcQ==,type:str]
            username: ENC[AES256_GCM,data:6c1op1In1QcY4U6IFYCSDvg=,iv:CeifK0z8C4a+ps1QGLyvTahi+gNd/aV5o8Tnar01ylc=,tag:cr5GKPERW4F5NV1PNKfBNA==,type:str]
            password: ENC[AES256_GCM,data:lhlzJAcXFP51rXLiYQxAiw==,iv:WYdTQD4sQ01oilfVRR9ZFxYE8G8OcgtkK3CTIcBkWNQ=,tag:R7Kp8BoMsg6X/zvKtA8dwg==,type:str]
            auto-index-creation: ENC[AES256_GCM,data:KGTJnQ==,iv:RvKHK+YsC7fV3C0Cz2Fo0Dr72Y70Q+UMbvcPlAHlCpI=,tag:s+b6yvKRWKZ+big88UGNKw==,type:bool]
sentry:
    dsn: ENC[AES256_GCM,data:rCqtx7vf9pbuYcs8FDVGRw2BN8zAvO4ILXAAf7jF4aMgEKU27B5X9MrZ0NTby0SGUg/99q0hBGRiFX2SitVp6v9Q5ulpoovrrOc2tVNh2kPayAKQLlZ47Jz8JSGaD1E=,iv:VFyA/JQZ2PD2ppTvQd3c7jQF5MLtQq9tTkFdoNE6hIs=,tag:MR1WupVXdCfYE544NwYl5Q==,type:str]
    traces-sample-rate: ENC[AES256_GCM,data:aQ==,iv:nvxvQ1NrvkqV2m8X//5R0pCPv4tjyR/7rc0vMHbD8bs=,tag:oQXZULhQBaGRuWVD+3AyPQ==,type:int]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:992382730467:key/a195f3cb-f301-48b4-ba70-9ffb95f6ddd2
          created_at: "2024-12-25T05:42:21Z"
          enc: AQICAHhZgrxm0DnTWfKW65/rZF7H04iuSIwsXgTk9YAalC3+YQFnkiBt2VUkUujURkZ7ZHMeAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3kjjKQekU9YZVbcVAgEQgDvY+ghqSxP+pD+HonBFV7NIBXgxjM6D45R8VWcDzQ1YQM/ZIQsWzQKqKenDaxLT6qBGliPoS5hUolRfgg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-25T05:42:21Z"
    mac: ENC[AES256_GCM,data:4K+4ur4JwqqCoH2mDSUmZm9s7id/N/IVtDzVt7wbRUp/gVoC6HBwz54XdOPiPsqZv1lslRvycVsmpsPcQ3AIsHcqh1aB7kfyUgb78X2Gel08Dv//5TvNu292sF97A1wqnPMX0DHbeKHfn38d1aO3/Pe8jt+3+lRzq3wooZpSycs=,iv:DrROaHxjr6NQrl2ob7+fwXaWaXbQcZ2U3q1YO2WbHIE=,tag:C411l6JEuP4tpM6f4Khvhg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
