kogo-api:
    authenticate: ENC[AES256_GCM,data:gAE7bcPxuYVSJsgHbzGwPbRpv9xL9QA1z2M5dA5HAw5TAEPEHlq2oXSbnWkwAa0=,iv:0JL5UlyvuXm8wrfZHTuFLBTQxVi8JiKCUm5pWOGuDLg=,tag:SwXKerS/m76HO3Y3Vo2xgQ==,type:str]
    getSchools: ENC[AES256_GCM,data:VUeDXMsISWW9EEBplScBp5XDtjddln8X9TVDO7D99jCsLen+/XU1nrnv,iv:iFETUxh/XHuE78eqER5lhgxYlTShRmNgWDD0+vd4A7c=,tag:VRla7rc7n/7a/dU5lNt0Nw==,type:str]
spring:
    data:
        mongodb:
            database: ENC[AES256_GCM,data:mhOmCbZRhJoubhx9pUA0JzbK0lM=,iv:OTrC72b4CwfUAKSqX3+9Ksl2yWeEZpym/DHaGyu36+o=,tag:2y5oyCjcXDWITKyTUSAojQ==,type:str]
            uri: ENC[AES256_GCM,data:lH0AWf1eA2rlBQw49g2w0cw6a4Z3y6foMxB3+IPpRrZgiXO8SLHR4Pupa9A3tzF4ak2RDWJmdNO91xykkBXbG0UK2Np+jgflbwrJQAXbrZcOzXZgkmHIKQEcfj8qw5Pb8dR6OsUpYWJwhnGzHV76vpW8HfeMcrxjpTG6dZj+ZkLm7DthEykJUkQl5dGvzlpaImjuANa37bm3IQPAaYNrX0WLCO2I1DPy75tEGkpGXH0Y,iv:ZpSNpHBDJaU+TmfiR9cNi3pDf8KT2q+N3UoXCv9pB2Q=,tag:WNLNfOV2cxKgJ3UbRafcog==,type:str]
            username: ENC[AES256_GCM,data:ian4hshg7z64bEIiLnSyoGY=,iv:K+qI9mugSjr7qKKaoT4tnWRQtTo0dUjm4KjHAX7P95U=,tag:MqVrFNxWnLlmd+CPVJNNbA==,type:str]
            password: ENC[AES256_GCM,data:8Rc9xnk94R05ZcHSv3xQVw==,iv:r7DIjM0r+5XS5L2mUIIuuNBGtY/JHC9YAFP95gSt1Rc=,tag:QzlmIxurgwzTSrEvAG/+wg==,type:str]
            auto-index-creation: ENC[AES256_GCM,data:aFxV8g==,iv:m13ymdgVuIkXiYlYZMgQUReLGRA1SammptMdNSivQoc=,tag:PCnDL5m7z5U7O05g4cNBnQ==,type:bool]
sentry:
    dsn: ENC[AES256_GCM,data:/i/Cp1KlyVDrEzvq7hm8TF41gVxpmc9S+/EEYWwIZdUAf4fhDVx8QHU8Y+eEx92EpVS0U3fX3162bfgXz9+mwqQSRSsvRS2Men7M2YaxR6m8gp0TdF7GE9RumqzkNJI=,iv:i0y1mDKcIrIObLlgjOYUc4lajm/tYoMz8/tf5CIDAek=,tag:5BPe4llh2NfFnZWgEznAcg==,type:str]
    traces-sample-rate: ENC[AES256_GCM,data:Aw==,iv:NQACaItYZWjyUIqFNsqAO0YcWgc03l7FHg9DETK5iPk=,tag:TFkeAhm8Xc7h1c7TagKB7g==,type:int]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:992382730467:key/a195f3cb-f301-48b4-ba70-9ffb95f6ddd2
          created_at: "2025-01-10T18:18:21Z"
          enc: AQICAHhZgrxm0DnTWfKW65/rZF7H04iuSIwsXgTk9YAalC3+YQGawP8AjveoSlc4r/jTUh94AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMfIlDSdITdF/kGRqzAgEQgDsDUp+oVvtO6X3Gm1n213BYN6lqcygL1n3Pq2bNTni+S+e4+YWX8Le++d+YB13bPfrwVMe5vQLX+/6blw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-10T18:18:21Z"
    mac: ENC[AES256_GCM,data:FA5zBpDiD6TRgVFJ9s6eo7U8UC0HosyfgMRqlKR2li4lm2Jghob3tw1Czjbu7aEz/Aa/EVtOJj27exbYjhST04C0K/h9eH/lCUfd1NTcpa2Lh4COKR1MVqOiG0MSaMvpOY69Roo4IHa67yi9AfN3eD7vATK0xK1VHgI+nWZY1cs=,iv:83IMAJEZi5hNgoaZmn3C0tfh9DMdtxIQejTeM9iYz7I=,tag:6CQQ/kHfpzne8SXAoCTnBA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
