kogo-api:
    authenticate: ENC[AES256_GCM,data:AN2k+Ej6KkuqtaLL2Vrt/O8yIUoX1pRS9b5j4oGNpKwo/Rw/8ij7j0lFIPFAb1o=,iv:Ncg1L4Xwnw/yl4KA2vAX9ZpSj78YZQwHOxXhOJjQPbM=,tag:Bd4LprhftMqL0hKZsc7zPQ==,type:str]
    getSchools: ENC[AES256_GCM,data:wLKdL/Y1a+xwC66veKU1HeO5rURj67Q4BUTVTQ3OdYacJI5l1n2m3cjm,iv:XyBY97DwmkGV/IMTKjYdT7FCOrmwl/H0XyV7iLI8JV4=,tag:e2gbN0u2XGhxpcoUutpKJA==,type:str]
spring:
    data:
        mongodb:
            database: ENC[AES256_GCM,data:KzXixCSRb7yjDi6Q2RhhcFqNon8=,iv:loqKh8u7SyLP/G3iKVsa9SNPHIByrtZ7RcG9h22j2us=,tag:6izh9nhsPd33Ul4cbE48dQ==,type:str]
            uri: ENC[AES256_GCM,data:D6Qy4xRMGrUaRUyg23gCckhIo7QfmngFJow7xdCBb1zQqDxIsd/sVFsSriqkZrSoVR1xqcasJ6C0XfkkYkH77mFWiCcZXkmQEj7RUvSwoofmS+Qv6FBffYV90ed/NXr3Gvblp4QfgpuRGmeM9OEbX7z101hW+DtFt0YKquVxmrNWyr/4GZmCaw4iR3CNPjrVQUZe0DzSOEDq53AlJD3D+ny0s6IHjYRF+VtQiSxUvx2U1zw=,iv:CQvpTl/WfsLZCxU1Z0SKGs9zjEF83DFieskYLTxnvpY=,tag:HCj3HKysliDPkwA0ejZteg==,type:str]
            username: ENC[AES256_GCM,data:Ns+ttYHlr7d78vWp2WMVgH4=,iv:FSMTu13sajYE4K/xKJyfuwzmHDG2LE2h+Ic4nD5aCQg=,tag:yFVt+ccg8uS+iOZsGIrc+w==,type:str]
            password: ENC[AES256_GCM,data:E//8Tak5/74l+Qkn2creOg==,iv:CBuRKy0xkwzYaeOKHoyhfTrSiZLH5tbjrp09Ib6Sq94=,tag:Njb43+Aecy4aiExT6q8Etw==,type:str]
            auto-index-creation: ENC[AES256_GCM,data:EFNJqQ==,iv:DtZ3HhdgwJjbtFWuf4+e7fh5bEbC9zTZm7oPCO2dbRU=,tag:+Vr00sz9bVJBcftyWDC5hQ==,type:bool]
sentry:
    dsn: ENC[AES256_GCM,data:MkXHfE0REqtYOXe2gQQtIUhNq6nQ/9/LRFuf89QNP82sPMZVeifV9Q+Z8PyBDU3xStJ0ZvhZb4P2XechAK6FImgKaOAxDIMByzydsIFEedTJfr9O6zizII9oU1sBXFc=,iv:Ekge04DeVZo1xUWU18Y1K9ABqB2tpDLgq5oSA+mG0KU=,tag:X//GY+T2/xxIkESNxTcesg==,type:str]
    traces-sample-rate: ENC[AES256_GCM,data:8w==,iv:DRzppZ9my4cTGpTmAnUEUTG/xiNbNzFNHI8Xx9Pa6sE=,tag:+6srlfEvS8zhkcEEV2zADQ==,type:int]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:992382730467:key/a195f3cb-f301-48b4-ba70-9ffb95f6ddd2
          created_at: "2024-12-27T20:06:46Z"
          enc: AQICAHhZgrxm0DnTWfKW65/rZF7H04iuSIwsXgTk9YAalC3+YQHvR0ozC08VginFtjIDdRh4AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMeHeSvBZW0JlXdmh7AgEQgDvcEr6FdWIAc0Z8T7Bjeqw71k3enSzelu8wG5GIn9R21dP+t5/UuXm8+vYlciESo/Sr93bbOR/LxZ/c4Q==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-27T20:06:46Z"
    mac: ENC[AES256_GCM,data:DJ9KBtUqiAI8vCGW3lnn7z43xVxIjKr/3pYythiFJQJi8pGrOORpLt9RV7FmNnjsSEuAM38MfcpqGaH6c/04+ua1bIJtQT5XQoFyc/xa+1buNaksTwS2xwsYEDUZUmy7+h5Fn88hJewUc9cOjoeIJY58uCfOek2TKLAWjiPOgQE=,iv:vwvEuOE/ZL1lZC0IybZJyCom6MGN+hAuZxedPjgjqFo=,tag:hWq69/gbHGYravAGhXn9YQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
